spring:
  application:
    name: nacos-dubbo-provider
dubbo:
  scan:
    base-packages: com.sasu.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  service:
    version: 1.0.0